[technote]
id = "TSTN-053"
series_id = "TSTN"
canonical_url = "https://tstn-053.lsst.io"
github_url = "https://github.com/lsst-tstn/tstn-053"
github_default_branch = "main"
date_created = 2025-05-05T19:58:27Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Brian J."
name.family = "Brondel"
internal_id = "brondelbj"
orcid = "https://orcid.org/0009-0005-3510-6248"

[[technote.authors.affiliations]]
name = "Vera C. Rubin Observatory/NSF NOIRLab"
internal_id = "RubinOpsC"
address = "Casilla 603, La Serena, Chile"

[[technote.authors]]
name.given="Fritz"
name.family="Mueller"
internal_id = "muellerf"
ocrid = "https://orcid.org/0000-0002-7061-4644"

[[technote.authors.affiliations]]
name = "SLAC National Accelerator Laboratory"
internal_id = "SLAC"
address = "2575 Sand Hill Rd., Menlo Park, CA 94025, USA"
